### ISSUE TITLE
Useless wrapping

### ISSUE THREAD

**Issue by sbilyi** [tpidgur/CoffeeMachineTDD1#3]
`BeverageMachineTest.passBanknoteTest`
`assertThat(userMoney, is(Arrays.asList(new Banknote[]{Banknote.FIFTY, Banknote.FIVE, Banknote.TEN})));
`
can be replaced with 
`assertThat(userMoney, is(Arrays.asList(Banknote.FIFTY, Banknote.FIVE, Banknote.TEN)));
`

**Comment by tpidgur** [comment]
Removed useless wrapping occured in BeverageMachineTest class.
