### ISSUE TITLE
Missplaced initialization

### ISSUE THREAD

**Issue by sbilyi** [tpidgur/CoffeeMachineTDD1#6]
```
  /**
     * initializes banknotes and drinks map with initial values
     */ {
        banknotes.put(Banknote.ONE, 10);
        banknotes.put(Banknote.TWO, 10);
        banknotes.put(Banknote.FIVE, 10);
        banknotes.put(Banknote.TEN, 10);
        banknotes.put(Banknote.TWENTY, 10);
        banknotes.put(Banknote.FIFTY, 10);
        drinks.put(BeverageType.LATTE, 10);
        drinks.put(BeverageType.MACHIATO, 10);
        drinks.put(BeverageType.AMERICANO, 10);
    }
```

You can use constructors for this, I didn't expect `hasAnyMoneyForChangeTest` will pass until I checked whole `BeverageMachine` class....sad

**Comment by tpidgur** [comment]
Renamed methods from  'hasAnyMoneyForChange()' to 'hasMachineBanknotesForChange()'.
Istead of passing 2 collections as arguments in a constructor, the method init() has been created, that puts the initial values in collections. I want the field 'Map<Banknote, Integer> banknotes = new TreeMap<>(Collections.reverseOrder())'  to be a TreeMap with Banknotes ordered in descending order (). THe purpose for doing this lies in method that gives change. It requires the ordered collection.
